package com.myspace.finanmovilsa.model.bo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Datime {

	public String formatted;

	private java.lang.String timestamp;

	public String getFormatted() {
		return formatted;
	}

	public Datime() {
	}

	public java.lang.String getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(java.lang.String timestamp) {
		this.timestamp = timestamp;
	}

	public Datime(java.lang.String formatted, java.lang.String timestamp) {
		this.formatted = formatted;
		this.timestamp = timestamp;
	}

}